name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Docker Buildx
      uses:docker/setup-buildx-action@v2

    - name: Login to Docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #used only if pushing images to Docker Hub

    - name: Build and push Docker image
      run: |
        docker build --tag savannah_container .
        docker run -d \
          - e POSTGRES_USER=${{ SECRETS.POSTGRES_USER }} \
          - e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          - e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          savannah_container

    - name: Verify Container is running
      run: docker ps
